using System.ServiceModel;
using System.ServiceModel.Web;

namespace HomeCloudService
{
    [ServiceContract()]
    public interface ISyncService
    {
        /// <summary>
        /// Post an image and write to disk.
        /// It validates the token, if it is valid it performs the following steps:
        /// - Transform the image base 64 to byte array
        /// - Writes the file to disk to the sync folder/folderName and the fileName
        /// - Update the the last sync date with the lastModified param (which must be the last modification date of the file)
        /// - If idPart is not null or empty, it saves the imageBase64 string in memory as part of a file which need to be sent in chunks.
        ///   All the chunks should be merge and writen to disk when an idPart with empty imageBase64 field is sent (see the example below).
        ///   
        ///   Example:
        ///     PostImage("base64StringChunk1", "tokenString", "image1.png", "folder", "2018-04-01 10:00:00", "partString")
        ///     PostImage("base64StringChunk2", "tokenString", "image1.png", "folder", "2018-04-01 10:00:00", "partString")
        ///     PostImage("base64StringChunk3", "tokenString", "image1.png", "folder", "2018-04-01 10:00:00", "partString")
        ///     PostImage("", "tokenString", "image1.png", "folder", "2018-04-01 10:00:00", "partString")
        /// </summary>
        /// <param name="imageBase64">Base64 string of the file or chunk</param>
        /// <param name="token">The token which identified the user. This token have been generated by Login service.</param>
        /// <param name="fileName">The file name of the file.</param>
        /// <param name="folderName">The folder in which the file will be saved.</param>
        /// <param name="lastModified">The last modification date of the file.</param>
        /// <param name="idPart">When this param is informed it means that this is a chunk of a file.</param>
        [OperationContract]
        [WebInvoke(Method = "POST"
            , BodyStyle = WebMessageBodyStyle.Wrapped
            , RequestFormat = WebMessageFormat.Json
            , ResponseFormat = WebMessageFormat.Json
            , UriTemplate = "New")]
        void PostImage(string imageBase64, string token, string fileName, string folderName, string lastModified, string idPart);

        /// <summary>
        /// Service used to validate the credentials and get the token that need to be used to call the other services.
        /// </summary>
        /// <param name="userName">The user name.</param>
        /// <param name="password">The password.</param>
        /// <returns>An string which identifies the user.</returns>
        [OperationContract]
        [WebInvoke(Method = "POST"
            , BodyStyle = WebMessageBodyStyle.Wrapped
            , RequestFormat = WebMessageFormat.Json
            , ResponseFormat = WebMessageFormat.Json
            , UriTemplate = "Login")]
        string Login(string userName, string password);

        /// <summary>
        /// Service used to the the last synchronization date which will be used by the client to get the files from this date.
        /// </summary>
        /// <param name="token">The token which identified the user. This token have been generated by Login service.</param>
        /// <returns>Last synchronization date.</returns>
        [OperationContract]
        [WebInvoke(Method = "POST"
            , BodyStyle = WebMessageBodyStyle.Wrapped
            , RequestFormat = WebMessageFormat.Json
            , ResponseFormat = WebMessageFormat.Json
            , UriTemplate = "LastUpdate")]
        string GetLastSync(string token);
    }
}
